#!/bin/bash
# Definition des alias de compilation
alias gccf="gcc -Wall -Wextra -Werror"
alias g++f="g++ -Wall -Wextra -Werror"

# Definition des alias
alias purgevim="rm -f $HOME/.config/nvim/tmp/*"

alias ta="tmux attach"

# git
alias ga="git add"
alias gb="git branch"
alias gcm="git commit -m"
alias gco="git checkout"
alias gpl="git pull"
alias gps="git push"
alias gm="git merge"
alias gu="git add -u"

# Replace ls with exa
exa $HOME >/dev/null 2>&1
if [[ $? == 0 ]]; then
    alias ls=exa
    alias ll="ls -l --group --git"
    alias la="ll -a"
    alias lg="ll --grid"
    alias lt="ll --tree"
fi
